version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
    - method: pip
      path: ./deepcell_release
    - requirements: docs/requirements.txt
